---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
Code is compiled in R. Since R studio crashed and not working PA1_template.md amd PA1_template.HTML could not be generated
---


## Loading and preprocessing the data
library(ggplot2)
library(plyr)
if(!file.exists('activity.csv')){
    unzip('activity.zip')
}
activityData <- read.csv('activity.csv')

## Processing the data

activityData$day <-weekdays(as.Date(activityData$date))
activityData$DateTime <- as.POSIXct(activityData$date, format="%Y-%m-%d")
clean <- activityData[!is.na(activityData$steps),]

## Calculate total number of steps taken per day?

sumtable <- aggregate(activityData$steps ~ activityData$date, FUN=sum,)
colnames(sumtable) <- c("Date","Steps")

## Make a histogram of the total number of steps taken each day

hist(sumtable$Steps, breaks =5, xlab ="Steps",main ="Total Steps per Day")

## Histogram to be referred in the attached .pdf file

## Calculate and report the mean and median total number of steps taken per day

as.integer(mean(sumtable$Steps))
## [1] 10766

as.integer(median(sumtable$Steps))
## [1] 10765


## What is the average daily activity pattern?

averageStepsPerTimeBlock <- aggregate(x=list(meanSteps=activityData$steps), by=list(interval=activityData$interval), FUN=mean, na.rm=TRUE)

1. Make a time series plot

ggplot(data=averageStepsPerTimeBlock, aes(x=interval, y=meanSteps)) +
    geom_line() +
    xlab("5-minute interval") +
    ylab("average number of steps taken") 

## Plot to be referred in attached pdf file

2. Which 5-minute interval, on average across all the days in the dataset, contains the maximum number of steps?

mostSteps <- which.max(averageStepsPerTimeBlock$meanSteps)
timeMostSteps <-  gsub("([0-9]{1,2})([0-9]{2})", "\\1:\\2", averageStepsPerTimeBlock[mostSteps,'interval'])

## Most Steps at: 8:35

## Imputing missing values

1. Calculate and report the total number of missing values in the dataset

numMissingValues <- length(which(is.na(activityData$steps)))
## Number of missing values: 2304

2. Devise a strategy for filling in all of the missing values in the dataset.

## My strategy for filling in NAs will be to substitute the missing steps with the average 5 minute interval based on the day of the week.

## Create the average number of steps per weekday and interval

avgtable <- ddply(clean, .(interval,day), summarize, Avg = mean(steps))

## Create dataset with all NAs for substitution

nadata <- activityData[is.na(activityData$steps), ]

## Merge NA data with average weekday interval for substitution

newdata <- merge(nadata, avgtable, by= c("interval", "day"))

3. Create a new dataset that is equal to the original dataset but with the missing data filled in.

## Reorder the new substituded data in the same format as clean data set
newdata2<- newdata[,c(6,4,1,2,5)]
colnames(newdata2)<- c("steps", "date", "interval", "day", "DateTime")

##Merge the NA averages and non NA data together
mergeData <- rbind(clean, newdata2)

4. Make a histogram of the total number of steps taken each day

##Create sum of steps per date to compare with step 1
sumTable2 <- aggregate(mergeData$steps ~ mergeData$date, FUN=sum, )
colnames(sumTable2)<- c("Date", "Steps")

## Mean of Steps with NA data taken care of
as.integer(mean(sumTable2$Steps))
##[1] 10821

## Median of Steps with NA data taken care of
as.integer(median(sumTable2$Steps))
##[1] 11015

## Creating the histogram of total steps per day, categorized by data set to show impact
hist(sumTable2$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Fixed", col="Black")
hist(sumTable$Steps, breaks=5, xlab="Steps", main = "Total Steps per Day with NAs Fixed", col="Grey", add=T)
legend("topright", c("Imputed Data", "Non-NA Data"), fill=c("black", "grey") )

## Are there differences in activity patterns between weekdays and weekends?
1. Create a new factor variable in the dataset with two levels – “weekday” and “weekend” indicating whether a given date is a weekday or weekend day.

mergeData$DayCategory <- ifelse(mergeData$day %in% c("Saturday", "Sunday"), "Weekend", "Weekday")

2. Make a panel plot containing a time series plot

library(lattice) 
## Warning message: package ‘lattice’ was built under R version 3.3.2

## Summarize data by interval and type of day
intervalTable2 <- ddply(mergeData, .(interval, DayCategory), summarize, Avg = mean(steps))

##Plot data in a panel plot
xyplot(Avg~interval|DayCategory, data=intervalTable2, type="l",  layout = c(1,2),
       main="Average Steps per Interval Based on Type of Day", 
       ylab="Average Number of Steps", xlab="Interval")
